name: Auto Comment
on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue comment ${{ github.event.issue.number }} -b "Thank you for your contribution!" -R ${{ github.repository }}
