name: Auto Comment
on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment ${{ github.event.issue.number }} --body "Thank you for your contribution!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}